config/routes.rb
Rails.application.routes.draw do
  root to: 'years#index'
  resources :years do
    resources :lookslikes
  end
end

app/models/lookslike.rb
class Lookslike < ActiveRecord::Base
  belongs_to :year

  def next
    Lookslike.where("id > ?", id).first
  end

  def prev
    Lookslike.where("id < ?", id).last
  end
end

app/models/year.rb
class Year < ActiveRecord::Base
  has_many :lookslikes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lookslikes_controller.rb
class LookslikesController < ApplicationController
  def index
    @lookslikes = Lookslike.all
  end

  def show
    @years = Year.all
    @year = Year.find(params[:year_id])
    @lookslike = @year.lookslikes.find(params[:id])
  end
end

app/controllers/years_controller.rb
class YearsController < ApplicationController
  def index
    @years = Year.all
  end

  def show
    @years = Year.all
    @year = Year.find(params[:id])
    @lookslikes = @year.lookslikes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name='March Sadness' content='What Famout People in Sports Look Like'>
  <!-- jQuery -->
  <script   src="http://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>
  <!-- Bootstrap CDN -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Merriweather" rel="stylesheet">
  <title>March Sadness</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>

  <!-- Google Analytics -->
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-86946985-1', 'auto');
  ga('send', 'pageview');
  </script>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="http://ssatyal.github.io/" target="_blank">SS</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <%@years.reverse_each do |y|%>
          <li><%=link_to "#{y.year}", y%></li>
          <%end%>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%=link_to "Home", years_path%></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<%= yield %>

</body>
</html>

app/views/lookslikes/show.html.erb
<div class="row text-center navigate-show-secondary">
  <div class="col-sm-4">
    <%= link_to raw('<i class="fa fa-arrow-left" aria-hidden="true"></i>'), year_lookslike_path(@lookslike.year, @lookslike.prev), :class => "btn btn-primary col-sm-12 small-button" if @lookslike.prev && @lookslike.prev.year.year == @lookslike.year.year%>
  </div>
  <div class="col-sm-4" id="counter">
    <%=@lookslike.id + 1 - @year.lookslikes.first.id%> / <%=@year.lookslikes.last.id - @year.lookslikes.first.id + 1%>
  </div>
  <div class="col-sm-4">
    <%= link_to raw('<i class="fa fa-arrow-right" aria-hidden="true"></i>'), year_lookslike_path(@lookslike.year, @lookslike.next), :class => "btn btn-primary col-sm-12 small-button" if @lookslike.next && @lookslike.next.year.year == @lookslike.year.year %>
  </div>
</div>
<h2 class="text-center"><%=@lookslike.name%></h2>
<div class="text-center lookslike-text"><%=@lookslike.looks_like%></div>
<div class="lookslike-img-container text-center">
  <img class="lookslike-img" src="<%=@lookslike.photo_url%>">
</div>
<div class="row text-center navigate-show-primary">
  <div class="col-sm-4">
    <%= link_to raw('<i class="fa fa-arrow-left" aria-hidden="true"></i>'), year_lookslike_path(@lookslike.year, @lookslike.prev), :class => "btn btn-primary col-sm-12" if @lookslike.prev && @lookslike.prev.year.year == @lookslike.year.year%>
  </div>
  <div class="col-sm-4" id="counter">
    <%=@lookslike.id + 1 - @year.lookslikes.first.id%> / <%=@year.lookslikes.last.id - @year.lookslikes.first.id + 1%>
  </div>
  <div class="col-sm-4">
    <%= link_to raw('<i class="fa fa-arrow-right" aria-hidden="true"></i>'), year_lookslike_path(@lookslike.year, @lookslike.next), :class => "btn btn-primary col-sm-12" if @lookslike.next && @lookslike.next.year.year == @lookslike.year.year %>
  </div>
</div>
</div>

app/views/years/index.html.erb
<h2 class="text-center" id="home-header">MARCH SADNESS</h2>
<div class="text-center">
  <div id="splash">
  </div>
</div>
<h3 class="text-center" id="tagline">What Famous People in Sports Look Like</h3>
<% @years.reverse_each do |year| %>
  <div class="text-center year-link">
    <h3 class="year-index-year">» <%= link_to year.year, year %></h3>
  </div>
<% end %>
<hr>
<h3 class="text-center hosts-name">Dan Le Batard</h3>
<h4 class="text-center hosts-lookslike">Looks like he has a bag of nickels in his cheeks.</h4>
<div class="lookslike-img-container text-center">
  <img class="lookslike-img" src="http://i.imgur.com/KwUjA7u.jpg?1">
</div>
<h3 class="text-center hosts-name">Stugotz</h3>
<h4 class="text-center hosts-lookslike">Looks really unhealthy.</h4>
<div class="lookslike-img-container text-center">
  <img class="lookslike-img" src="http://i.imgur.com/JhRe7tX.png?1">
</div>

app/views/years/show.html.erb
<h1 class="text-center" id="year-show-year"><%= @year.year %></h1>
<div class="row">
  <% @year.lookslikes.each do |ll| %>
    <div class="col-sm-4 year-looks-like">
      <%= link_to year_lookslike_path(@year, ll) do %>
      <div class="year-show-img" style="background-image:url(<%=ll.photo_url%>)">
      </div>
      <div class="year-show-name text-center">
        <div class="year-show-link-text">
          <%=ll.name%>
        </div>
      </div>
    </div>
    <% end %>
  <% end %>
</div>